In [1]:
import numpy as np

In [60]:
class MLP:
    def __init__(self, input_size = 28*28, hidden_layers_sizes = [16*10, 8*10, 2*10], output_size = 10):
        self.output_size = output_size
        self.sigma_activation =  lambda x: 1/ (np.exp(-x) + 1)
        self.sigma_gradient = lambda x: self.sigma_activation(x)*self.sigma_activation(-x)
        self.layers_sizes = [input_size] + hidden_layers_sizes + [output_size]
        #Affine transformations between layers are performed by numpy matrices and arrays
        self.weights = []
        self.biases = []
        for i in range(len(self.layers_sizes) - 1):
            self.weights.append(np.random.rand(self.layers_sizes[i+1], self.layers_sizes[i]))
            self.biases.append(np.random.rand(self.layers_sizes[i+1], 1))
        self.activations = []
        self.gradients_of_weights = []
        self.gradients_of_biases = []
    def forward_propagat(self, data_in: np.array):
        data = self._prepare_input(data_in)
        self.activations = [data]
        for i in range(len(self.weights)):
            transform = self.weights[i]@self.activations[i] + self.biases[i]
            self.activations.append(self.sigma_activation(transform))
        return self.activations[-1]
        
    def _prepare_input(self, data_in: np.array):
        data_in.shape = (self.layers_sizes[0], -1) # + 1 is bias
        return data_in
    
    def _prepare_output(self, target: np.array):
        target.shape = (self.output_size, -1)
        if target.shape[1] != self.activations[-1].shape[1]:
            print("Number of samples of data and target do not match!!!")
        return target
    
    def backward_propagat(self, target):
        y = self._prepare_input(target)
        # Loss function is sum_{by samples}(<y - y', y - y'>) where y, y' \in R^d (d = 10)
        # As tr(A.T@B) = sum_ij(a_ij*b_ij) loss function is tr((Y_pr - Y).T@(Y_pr - Y)). So L(Y_pr) = tr((Y_pr - Y).T@(Y_pr - Y))
        # Gradient of L is 2(Y_pr - Y) in terms of [DL](H) = tr(2(Y_pr - Y)H)
        gradient_of_loss_function = 2*(self.activations[-1] - y) * self.sigma_gradient(self.weights[-1]@self.activations[-2] + self.biases[-1])
        self.gradients_of_weights = []
        self.gradients_of_biases = []
        for i in reversed(range(len(self.weights))):
            
            
        


In [61]:
mlp = MLP(2, [2, 1], 1)

In [62]:
a_1 = np.array([0, 0.5])
a_5 = np.random.rand(2, 5)

In [63]:
mlp.forward_propagat(a_1)

array([[0.77461097]])

In [64]:
mlp.forward_propagat(a_5)

array([[0.7748174 , 0.77481632, 0.77563976, 0.77522027, 0.77447037]])

In [30]:
a = np.array([[1, 2], [3, 4], [4, 6],])
b = np.array([[1, 2], [3, 4], [4, 6],])

In [31]:
print(a, '\n', b)

[[1 2]
 [3 4]
 [4 6]] 
 [[1 2]
 [3 4]
 [4 6]]


In [32]:
a*b

array([[ 1,  4],
       [ 9, 16],
       [16, 36]])

In [33]:
b = np.array([[1, 2], [3, 4], [4, 6],])

In [34]:
b.shape(-1,)

array([1, 2, 3, 4, 4, 6])

In [35]:
c = b

In [36]:
c *= 8

In [37]:
c

array([[ 8, 16],
       [24, 32],
       [32, 48]])

In [38]:
b

array([[ 8, 16],
       [24, 32],
       [32, 48]])